//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IFileSystem")]
    public interface IFileSystem {
        
        // CODEGEN: Параметр "GetAllFilesResult" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlArrayAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetAllFiles", ReplyAction="http://tempuri.org/IFileSystem/GetAllFilesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Client.ServiceReference.GetAllFilesResponse GetAllFiles(Client.ServiceReference.GetAllFilesRequest request);
        
        // CODEGEN: Параметр "userEmail" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetFileStream", ReplyAction="http://tempuri.org/IFileSystem/GetFileStreamResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Client.ServiceReference.GetFileStreamResponse GetFileStream(Client.ServiceReference.GetFileStreamRequest request);
        
        // CODEGEN: Параметр "userEmail" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetDirectory", ReplyAction="http://tempuri.org/IFileSystem/GetDirectoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Client.ServiceReference.GetDirectoryResponse GetDirectory(Client.ServiceReference.GetDirectoryRequest request);
        
        // CODEGEN: Параметр "userEmail" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetParentDirectory", ReplyAction="http://tempuri.org/IFileSystem/GetParentDirectoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Client.ServiceReference.GetParentDirectoryResponse GetParentDirectory(Client.ServiceReference.GetParentDirectoryRequest request);
        
        // CODEGEN: Параметр "GetDirectoryFilesResult" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlArrayAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetDirectoryFiles", ReplyAction="http://tempuri.org/IFileSystem/GetDirectoryFilesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Client.ServiceReference.GetDirectoryFilesResponse GetDirectoryFiles(Client.ServiceReference.GetDirectoryFilesRequest request);
        
        // CODEGEN: Контракт генерации сообщений с операцией UploadFile не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/UploadFile", ReplyAction="http://tempuri.org/IFileSystem/UploadFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Client.ServiceReference.UploadFileResponse UploadFile(Client.ServiceReference.FileUploadMessage request);
        
        // CODEGEN: Параметр "userEmail" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/DeleteFile", ReplyAction="http://tempuri.org/IFileSystem/DeleteFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Client.ServiceReference.DeleteFileResponse DeleteFile(Client.ServiceReference.DeleteFileRequest request);
        
        // CODEGEN: Параметр "path" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/CreateDirectory", ReplyAction="http://tempuri.org/IFileSystem/CreateDirectoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Client.ServiceReference.CreateDirectoryResponse CreateDirectory(Client.ServiceReference.CreateDirectoryRequest request);
        
        // CODEGEN: Параметр "userEmail" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/DeleteDirectory", ReplyAction="http://tempuri.org/IFileSystem/DeleteDirectoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Client.ServiceReference.DeleteDirectoryResponse DeleteDirectory(Client.ServiceReference.DeleteDirectoryRequest request);
        
        // CODEGEN: Параметр "GetDirectorySubDirectoriesResult" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlArrayAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetDirectorySubDirectories", ReplyAction="http://tempuri.org/IFileSystem/GetDirectorySubDirectoriesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Client.ServiceReference.GetDirectorySubDirectoriesResponse GetDirectorySubDirectories(Client.ServiceReference.GetDirectorySubDirectoriesRequest request);
        
        // CODEGEN: Параметр "userEmail" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/Move", ReplyAction="http://tempuri.org/IFileSystem/MoveResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Client.ServiceReference.MoveResponse Move(Client.ServiceReference.MoveRequest request);
        
        // CODEGEN: Параметр "GetFilePathResult" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetFilePath", ReplyAction="http://tempuri.org/IFileSystem/GetFilePathResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Client.ServiceReference.GetFilePathResponse GetFilePath(Client.ServiceReference.GetFilePathRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Service")]
    public partial class MyFile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int fileIdField;
        
        private bool fileIdFieldSpecified;
        
        private bool isDirectoryField;
        
        private bool isDirectoryFieldSpecified;
        
        private System.DateTime lastWriteTimeField;
        
        private bool lastWriteTimeFieldSpecified;
        
        private string nameField;
        
        private string pathField;
        
        private long sizeField;
        
        private bool sizeFieldSpecified;
        
        private FileStatus statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int FileId {
            get {
                return this.fileIdField;
            }
            set {
                this.fileIdField = value;
                this.RaisePropertyChanged("FileId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileIdSpecified {
            get {
                return this.fileIdFieldSpecified;
            }
            set {
                this.fileIdFieldSpecified = value;
                this.RaisePropertyChanged("FileIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool IsDirectory {
            get {
                return this.isDirectoryField;
            }
            set {
                this.isDirectoryField = value;
                this.RaisePropertyChanged("IsDirectory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsDirectorySpecified {
            get {
                return this.isDirectoryFieldSpecified;
            }
            set {
                this.isDirectoryFieldSpecified = value;
                this.RaisePropertyChanged("IsDirectorySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime LastWriteTime {
            get {
                return this.lastWriteTimeField;
            }
            set {
                this.lastWriteTimeField = value;
                this.RaisePropertyChanged("LastWriteTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastWriteTimeSpecified {
            get {
                return this.lastWriteTimeFieldSpecified;
            }
            set {
                this.lastWriteTimeFieldSpecified = value;
                this.RaisePropertyChanged("LastWriteTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
                this.RaisePropertyChanged("Path");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("Size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SizeSpecified {
            get {
                return this.sizeFieldSpecified;
            }
            set {
                this.sizeFieldSpecified = value;
                this.RaisePropertyChanged("SizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public FileStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Service")]
    public enum FileStatus {
        
        /// <remarks/>
        Download,
        
        /// <remarks/>
        Upload,
        
        /// <remarks/>
        Delete,
        
        /// <remarks/>
        NotChange,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Service")]
    public partial class DynaTreeNode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isFolderField;
        
        private bool isFolderFieldSpecified;
        
        private bool isLazyField;
        
        private bool isLazyFieldSpecified;
        
        private int keyField;
        
        private bool keyFieldSpecified;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool isFolder {
            get {
                return this.isFolderField;
            }
            set {
                this.isFolderField = value;
                this.RaisePropertyChanged("isFolder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isFolderSpecified {
            get {
                return this.isFolderFieldSpecified;
            }
            set {
                this.isFolderFieldSpecified = value;
                this.RaisePropertyChanged("isFolderSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool isLazy {
            get {
                return this.isLazyField;
            }
            set {
                this.isLazyField = value;
                this.RaisePropertyChanged("isLazy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isLazySpecified {
            get {
                return this.isLazyFieldSpecified;
            }
            set {
                this.isLazyFieldSpecified = value;
                this.RaisePropertyChanged("isLazySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool keySpecified {
            get {
                return this.keyFieldSpecified;
            }
            set {
                this.keyFieldSpecified = value;
                this.RaisePropertyChanged("keySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllFiles", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllFilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public GetAllFilesRequest() {
        }
        
        public GetAllFilesRequest(string userEmail, string userPass) {
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllFilesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllFilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Service", IsNullable=false)]
        public MyFile[] GetAllFilesResult;
        
        public GetAllFilesResponse() {
        }
        
        public GetAllFilesResponse(MyFile[] GetAllFilesResult) {
            this.GetAllFilesResult = GetAllFilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileStream", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileStreamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int fileId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public GetFileStreamRequest() {
        }
        
        public GetFileStreamRequest(int fileId, string userEmail, string userPass) {
            this.fileId = fileId;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileStreamResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileStreamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream GetFileStreamResult;
        
        public GetFileStreamResponse() {
        }
        
        public GetFileStreamResponse(System.IO.Stream GetFileStreamResult) {
            this.GetFileStreamResult = GetFileStreamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDirectory", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDirectoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int directoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public GetDirectoryRequest() {
        }
        
        public GetDirectoryRequest(int directoryId, string userEmail, string userPass) {
            this.directoryId = directoryId;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDirectoryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDirectoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference.MyFile GetDirectoryResult;
        
        public GetDirectoryResponse() {
        }
        
        public GetDirectoryResponse(Client.ServiceReference.MyFile GetDirectoryResult) {
            this.GetDirectoryResult = GetDirectoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetParentDirectory", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetParentDirectoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int directoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public GetParentDirectoryRequest() {
        }
        
        public GetParentDirectoryRequest(int directoryId, string userEmail, string userPass) {
            this.directoryId = directoryId;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetParentDirectoryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetParentDirectoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Client.ServiceReference.MyFile GetParentDirectoryResult;
        
        public GetParentDirectoryResponse() {
        }
        
        public GetParentDirectoryResponse(Client.ServiceReference.MyFile GetParentDirectoryResult) {
            this.GetParentDirectoryResult = GetParentDirectoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDirectoryFiles", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDirectoryFilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int directoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool recursive;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public GetDirectoryFilesRequest() {
        }
        
        public GetDirectoryFilesRequest(int directoryId, bool recursive, string userEmail, string userPass) {
            this.directoryId = directoryId;
            this.recursive = recursive;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDirectoryFilesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDirectoryFilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Service", IsNullable=false)]
        public MyFile[] GetDirectoryFilesResult;
        
        public GetDirectoryFilesResponse() {
        }
        
        public GetDirectoryFilesResponse(MyFile[] GetDirectoryFilesResult) {
            this.GetDirectoryFilesResult = GetDirectoryFilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileUploadMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileUploadMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Client.ServiceReference.MyFile file;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream sourceStream;
        
        public FileUploadMessage() {
        }
        
        public FileUploadMessage(Client.ServiceReference.MyFile file, string userEmail, string userPass, System.IO.Stream sourceStream) {
            this.file = file;
            this.userEmail = userEmail;
            this.userPass = userPass;
            this.sourceStream = sourceStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse {
        
        public UploadFileResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int fileId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public DeleteFileRequest() {
        }
        
        public DeleteFileRequest(int fileId, string userEmail, string userPass) {
            this.fileId = fileId;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteFileResponse {
        
        public DeleteFileResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateDirectory", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateDirectoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string path;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public CreateDirectoryRequest() {
        }
        
        public CreateDirectoryRequest(string path, string userEmail, string userPass) {
            this.path = path;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateDirectoryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateDirectoryResponse {
        
        public CreateDirectoryResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteDirectory", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteDirectoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int directoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public DeleteDirectoryRequest() {
        }
        
        public DeleteDirectoryRequest(int directoryId, string userEmail, string userPass) {
            this.directoryId = directoryId;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteDirectoryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteDirectoryResponse {
        
        public DeleteDirectoryResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDirectorySubDirectories", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDirectorySubDirectoriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int directoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public GetDirectorySubDirectoriesRequest() {
        }
        
        public GetDirectorySubDirectoriesRequest(int directoryId, string userEmail, string userPass) {
            this.directoryId = directoryId;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDirectorySubDirectoriesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDirectorySubDirectoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Service", IsNullable=false)]
        public DynaTreeNode[] GetDirectorySubDirectoriesResult;
        
        public GetDirectorySubDirectoriesResponse() {
        }
        
        public GetDirectorySubDirectoriesResponse(DynaTreeNode[] GetDirectorySubDirectoriesResult) {
            this.GetDirectorySubDirectoriesResult = GetDirectorySubDirectoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Move", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int fileId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int directoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int isDirectory;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public MoveRequest() {
        }
        
        public MoveRequest(int fileId, int directoryId, int isDirectory, string userEmail, string userPass) {
            this.fileId = fileId;
            this.directoryId = directoryId;
            this.isDirectory = isDirectory;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MoveResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MoveResponse {
        
        public MoveResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFilePath", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFilePathRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int fileId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int isDirectory;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public GetFilePathRequest() {
        }
        
        public GetFilePathRequest(int fileId, int isDirectory, string userEmail, string userPass) {
            this.fileId = fileId;
            this.isDirectory = isDirectory;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFilePathResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFilePathResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetFilePathResult;
        
        public GetFilePathResponse() {
        }
        
        public GetFilePathResponse(string GetFilePathResult) {
            this.GetFilePathResult = GetFilePathResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileSystemChannel : Client.ServiceReference.IFileSystem, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileSystemClient : System.ServiceModel.ClientBase<Client.ServiceReference.IFileSystem>, Client.ServiceReference.IFileSystem {
        
        public FileSystemClient() {
        }
        
        public FileSystemClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileSystemClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileSystemClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileSystemClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference.GetAllFilesResponse Client.ServiceReference.IFileSystem.GetAllFiles(Client.ServiceReference.GetAllFilesRequest request) {
            return base.Channel.GetAllFiles(request);
        }
        
        public MyFile[] GetAllFiles(string userEmail, string userPass) {
            Client.ServiceReference.GetAllFilesRequest inValue = new Client.ServiceReference.GetAllFilesRequest();
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Client.ServiceReference.GetAllFilesResponse retVal = ((Client.ServiceReference.IFileSystem)(this)).GetAllFiles(inValue);
            return retVal.GetAllFilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference.GetFileStreamResponse Client.ServiceReference.IFileSystem.GetFileStream(Client.ServiceReference.GetFileStreamRequest request) {
            return base.Channel.GetFileStream(request);
        }
        
        public System.IO.Stream GetFileStream(int fileId, string userEmail, string userPass) {
            Client.ServiceReference.GetFileStreamRequest inValue = new Client.ServiceReference.GetFileStreamRequest();
            inValue.fileId = fileId;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Client.ServiceReference.GetFileStreamResponse retVal = ((Client.ServiceReference.IFileSystem)(this)).GetFileStream(inValue);
            return retVal.GetFileStreamResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference.GetDirectoryResponse Client.ServiceReference.IFileSystem.GetDirectory(Client.ServiceReference.GetDirectoryRequest request) {
            return base.Channel.GetDirectory(request);
        }
        
        public Client.ServiceReference.MyFile GetDirectory(int directoryId, string userEmail, string userPass) {
            Client.ServiceReference.GetDirectoryRequest inValue = new Client.ServiceReference.GetDirectoryRequest();
            inValue.directoryId = directoryId;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Client.ServiceReference.GetDirectoryResponse retVal = ((Client.ServiceReference.IFileSystem)(this)).GetDirectory(inValue);
            return retVal.GetDirectoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference.GetParentDirectoryResponse Client.ServiceReference.IFileSystem.GetParentDirectory(Client.ServiceReference.GetParentDirectoryRequest request) {
            return base.Channel.GetParentDirectory(request);
        }
        
        public Client.ServiceReference.MyFile GetParentDirectory(int directoryId, string userEmail, string userPass) {
            Client.ServiceReference.GetParentDirectoryRequest inValue = new Client.ServiceReference.GetParentDirectoryRequest();
            inValue.directoryId = directoryId;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Client.ServiceReference.GetParentDirectoryResponse retVal = ((Client.ServiceReference.IFileSystem)(this)).GetParentDirectory(inValue);
            return retVal.GetParentDirectoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference.GetDirectoryFilesResponse Client.ServiceReference.IFileSystem.GetDirectoryFiles(Client.ServiceReference.GetDirectoryFilesRequest request) {
            return base.Channel.GetDirectoryFiles(request);
        }
        
        public MyFile[] GetDirectoryFiles(int directoryId, bool recursive, string userEmail, string userPass) {
            Client.ServiceReference.GetDirectoryFilesRequest inValue = new Client.ServiceReference.GetDirectoryFilesRequest();
            inValue.directoryId = directoryId;
            inValue.recursive = recursive;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Client.ServiceReference.GetDirectoryFilesResponse retVal = ((Client.ServiceReference.IFileSystem)(this)).GetDirectoryFiles(inValue);
            return retVal.GetDirectoryFilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference.UploadFileResponse Client.ServiceReference.IFileSystem.UploadFile(Client.ServiceReference.FileUploadMessage request) {
            return base.Channel.UploadFile(request);
        }
        
        public void UploadFile(Client.ServiceReference.MyFile file, string userEmail, string userPass, System.IO.Stream sourceStream) {
            Client.ServiceReference.FileUploadMessage inValue = new Client.ServiceReference.FileUploadMessage();
            inValue.file = file;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            inValue.sourceStream = sourceStream;
            Client.ServiceReference.UploadFileResponse retVal = ((Client.ServiceReference.IFileSystem)(this)).UploadFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference.DeleteFileResponse Client.ServiceReference.IFileSystem.DeleteFile(Client.ServiceReference.DeleteFileRequest request) {
            return base.Channel.DeleteFile(request);
        }
        
        public void DeleteFile(int fileId, string userEmail, string userPass) {
            Client.ServiceReference.DeleteFileRequest inValue = new Client.ServiceReference.DeleteFileRequest();
            inValue.fileId = fileId;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Client.ServiceReference.DeleteFileResponse retVal = ((Client.ServiceReference.IFileSystem)(this)).DeleteFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference.CreateDirectoryResponse Client.ServiceReference.IFileSystem.CreateDirectory(Client.ServiceReference.CreateDirectoryRequest request) {
            return base.Channel.CreateDirectory(request);
        }
        
        public void CreateDirectory(string path, string userEmail, string userPass) {
            Client.ServiceReference.CreateDirectoryRequest inValue = new Client.ServiceReference.CreateDirectoryRequest();
            inValue.path = path;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Client.ServiceReference.CreateDirectoryResponse retVal = ((Client.ServiceReference.IFileSystem)(this)).CreateDirectory(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference.DeleteDirectoryResponse Client.ServiceReference.IFileSystem.DeleteDirectory(Client.ServiceReference.DeleteDirectoryRequest request) {
            return base.Channel.DeleteDirectory(request);
        }
        
        public void DeleteDirectory(int directoryId, string userEmail, string userPass) {
            Client.ServiceReference.DeleteDirectoryRequest inValue = new Client.ServiceReference.DeleteDirectoryRequest();
            inValue.directoryId = directoryId;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Client.ServiceReference.DeleteDirectoryResponse retVal = ((Client.ServiceReference.IFileSystem)(this)).DeleteDirectory(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference.GetDirectorySubDirectoriesResponse Client.ServiceReference.IFileSystem.GetDirectorySubDirectories(Client.ServiceReference.GetDirectorySubDirectoriesRequest request) {
            return base.Channel.GetDirectorySubDirectories(request);
        }
        
        public DynaTreeNode[] GetDirectorySubDirectories(int directoryId, string userEmail, string userPass) {
            Client.ServiceReference.GetDirectorySubDirectoriesRequest inValue = new Client.ServiceReference.GetDirectorySubDirectoriesRequest();
            inValue.directoryId = directoryId;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Client.ServiceReference.GetDirectorySubDirectoriesResponse retVal = ((Client.ServiceReference.IFileSystem)(this)).GetDirectorySubDirectories(inValue);
            return retVal.GetDirectorySubDirectoriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference.MoveResponse Client.ServiceReference.IFileSystem.Move(Client.ServiceReference.MoveRequest request) {
            return base.Channel.Move(request);
        }
        
        public void Move(int fileId, int directoryId, int isDirectory, string userEmail, string userPass) {
            Client.ServiceReference.MoveRequest inValue = new Client.ServiceReference.MoveRequest();
            inValue.fileId = fileId;
            inValue.directoryId = directoryId;
            inValue.isDirectory = isDirectory;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Client.ServiceReference.MoveResponse retVal = ((Client.ServiceReference.IFileSystem)(this)).Move(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference.GetFilePathResponse Client.ServiceReference.IFileSystem.GetFilePath(Client.ServiceReference.GetFilePathRequest request) {
            return base.Channel.GetFilePath(request);
        }
        
        public string GetFilePath(int fileId, int isDirectory, string userEmail, string userPass) {
            Client.ServiceReference.GetFilePathRequest inValue = new Client.ServiceReference.GetFilePathRequest();
            inValue.fileId = fileId;
            inValue.isDirectory = isDirectory;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Client.ServiceReference.GetFilePathResponse retVal = ((Client.ServiceReference.IFileSystem)(this)).GetFilePath(inValue);
            return retVal.GetFilePathResult;
        }
    }
}
