//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.FileSystemServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileSystemServiceReference.IFileSystem")]
    public interface IFileSystem {
        
        // CODEGEN: Параметр "GetAllFilesResult" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlArrayAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetAllFiles", ReplyAction="http://tempuri.org/IFileSystem/GetAllFilesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Site.FileSystemServiceReference.GetAllFilesResponse GetAllFiles(Site.FileSystemServiceReference.GetAllFilesRequest request);
        
        // CODEGEN: Параметр "userEmail" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetFileStream", ReplyAction="http://tempuri.org/IFileSystem/GetFileStreamResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Site.FileSystemServiceReference.GetFileStreamResponse GetFileStream(Site.FileSystemServiceReference.GetFileStreamRequest request);
        
        // CODEGEN: Параметр "userEmail" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetDirectory", ReplyAction="http://tempuri.org/IFileSystem/GetDirectoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Site.FileSystemServiceReference.GetDirectoryResponse GetDirectory(Site.FileSystemServiceReference.GetDirectoryRequest request);
        
        // CODEGEN: Параметр "userEmail" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetFile", ReplyAction="http://tempuri.org/IFileSystem/GetFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Site.FileSystemServiceReference.GetFileResponse GetFile(Site.FileSystemServiceReference.GetFileRequest request);
        
        // CODEGEN: Параметр "userEmail" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetParentDirectoryId", ReplyAction="http://tempuri.org/IFileSystem/GetParentDirectoryIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Site.FileSystemServiceReference.GetParentDirectoryIdResponse GetParentDirectoryId(Site.FileSystemServiceReference.GetParentDirectoryIdRequest request);
        
        // CODEGEN: Параметр "GetDirectoryFilesResult" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlArrayAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetDirectoryFiles", ReplyAction="http://tempuri.org/IFileSystem/GetDirectoryFilesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Site.FileSystemServiceReference.GetDirectoryFilesResponse GetDirectoryFiles(Site.FileSystemServiceReference.GetDirectoryFilesRequest request);
        
        // CODEGEN: Контракт генерации сообщений с операцией UploadFile не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/UploadFile", ReplyAction="http://tempuri.org/IFileSystem/UploadFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Site.FileSystemServiceReference.UploadFileResponse UploadFile(Site.FileSystemServiceReference.FileUploadMessage request);
        
        // CODEGEN: Параметр "userEmail" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/DeleteFile", ReplyAction="http://tempuri.org/IFileSystem/DeleteFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Site.FileSystemServiceReference.DeleteFileResponse DeleteFile(Site.FileSystemServiceReference.DeleteFileRequest request);
        
        // CODEGEN: Параметр "path" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/CreateDirectory", ReplyAction="http://tempuri.org/IFileSystem/CreateDirectoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Site.FileSystemServiceReference.CreateDirectoryResponse CreateDirectory(Site.FileSystemServiceReference.CreateDirectoryRequest request);
        
        // CODEGEN: Параметр "userEmail" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/DeleteDirectory", ReplyAction="http://tempuri.org/IFileSystem/DeleteDirectoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Site.FileSystemServiceReference.DeleteDirectoryResponse DeleteDirectory(Site.FileSystemServiceReference.DeleteDirectoryRequest request);
        
        // CODEGEN: Параметр "GetDirectorySubDirectoriesResult" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlArrayAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetDirectorySubDirectories", ReplyAction="http://tempuri.org/IFileSystem/GetDirectorySubDirectoriesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Site.FileSystemServiceReference.GetDirectorySubDirectoriesResponse GetDirectorySubDirectories(Site.FileSystemServiceReference.GetDirectorySubDirectoriesRequest request);
        
        // CODEGEN: Параметр "userEmail" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/Move", ReplyAction="http://tempuri.org/IFileSystem/MoveResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Site.FileSystemServiceReference.MoveResponse Move(Site.FileSystemServiceReference.MoveRequest request);
        
        // CODEGEN: Параметр "userEmail" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/Copy", ReplyAction="http://tempuri.org/IFileSystem/CopyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Site.FileSystemServiceReference.CopyResponse Copy(Site.FileSystemServiceReference.CopyRequest request);
        
        // CODEGEN: Параметр "newName" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/Rename", ReplyAction="http://tempuri.org/IFileSystem/RenameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Site.FileSystemServiceReference.RenameResponse Rename(Site.FileSystemServiceReference.RenameRequest request);
        
        // CODEGEN: Параметр "GetFilePathResult" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetFilePath", ReplyAction="http://tempuri.org/IFileSystem/GetFilePathResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Site.FileSystemServiceReference.GetFilePathResponse GetFilePath(Site.FileSystemServiceReference.GetFilePathRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Service")]
    public partial class MyFile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int fileIdField;
        
        private bool fileIdFieldSpecified;
        
        private bool isDirectoryField;
        
        private bool isDirectoryFieldSpecified;
        
        private System.DateTime lastWriteTimeField;
        
        private bool lastWriteTimeFieldSpecified;
        
        private string nameField;
        
        private int parentDirectoryIdField;
        
        private bool parentDirectoryIdFieldSpecified;
        
        private string pathField;
        
        private long sizeField;
        
        private bool sizeFieldSpecified;
        
        private FileStatus statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int FileId {
            get {
                return this.fileIdField;
            }
            set {
                this.fileIdField = value;
                this.RaisePropertyChanged("FileId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileIdSpecified {
            get {
                return this.fileIdFieldSpecified;
            }
            set {
                this.fileIdFieldSpecified = value;
                this.RaisePropertyChanged("FileIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool IsDirectory {
            get {
                return this.isDirectoryField;
            }
            set {
                this.isDirectoryField = value;
                this.RaisePropertyChanged("IsDirectory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsDirectorySpecified {
            get {
                return this.isDirectoryFieldSpecified;
            }
            set {
                this.isDirectoryFieldSpecified = value;
                this.RaisePropertyChanged("IsDirectorySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime LastWriteTime {
            get {
                return this.lastWriteTimeField;
            }
            set {
                this.lastWriteTimeField = value;
                this.RaisePropertyChanged("LastWriteTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastWriteTimeSpecified {
            get {
                return this.lastWriteTimeFieldSpecified;
            }
            set {
                this.lastWriteTimeFieldSpecified = value;
                this.RaisePropertyChanged("LastWriteTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ParentDirectoryId {
            get {
                return this.parentDirectoryIdField;
            }
            set {
                this.parentDirectoryIdField = value;
                this.RaisePropertyChanged("ParentDirectoryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ParentDirectoryIdSpecified {
            get {
                return this.parentDirectoryIdFieldSpecified;
            }
            set {
                this.parentDirectoryIdFieldSpecified = value;
                this.RaisePropertyChanged("ParentDirectoryIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
                this.RaisePropertyChanged("Path");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("Size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SizeSpecified {
            get {
                return this.sizeFieldSpecified;
            }
            set {
                this.sizeFieldSpecified = value;
                this.RaisePropertyChanged("SizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public FileStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Service")]
    public enum FileStatus {
        
        /// <remarks/>
        Download,
        
        /// <remarks/>
        Upload,
        
        /// <remarks/>
        Delete,
        
        /// <remarks/>
        NotChange,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Service")]
    public partial class DynaTreeNode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isFolderField;
        
        private bool isFolderFieldSpecified;
        
        private bool isLazyField;
        
        private bool isLazyFieldSpecified;
        
        private int keyField;
        
        private bool keyFieldSpecified;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool isFolder {
            get {
                return this.isFolderField;
            }
            set {
                this.isFolderField = value;
                this.RaisePropertyChanged("isFolder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isFolderSpecified {
            get {
                return this.isFolderFieldSpecified;
            }
            set {
                this.isFolderFieldSpecified = value;
                this.RaisePropertyChanged("isFolderSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool isLazy {
            get {
                return this.isLazyField;
            }
            set {
                this.isLazyField = value;
                this.RaisePropertyChanged("isLazy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isLazySpecified {
            get {
                return this.isLazyFieldSpecified;
            }
            set {
                this.isLazyFieldSpecified = value;
                this.RaisePropertyChanged("isLazySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool keySpecified {
            get {
                return this.keyFieldSpecified;
            }
            set {
                this.keyFieldSpecified = value;
                this.RaisePropertyChanged("keySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllFiles", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllFilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public GetAllFilesRequest() {
        }
        
        public GetAllFilesRequest(string userEmail, string userPass) {
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllFilesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllFilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Service", IsNullable=false)]
        public MyFile[] GetAllFilesResult;
        
        public GetAllFilesResponse() {
        }
        
        public GetAllFilesResponse(MyFile[] GetAllFilesResult) {
            this.GetAllFilesResult = GetAllFilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileStream", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileStreamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int fileId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public GetFileStreamRequest() {
        }
        
        public GetFileStreamRequest(int fileId, string userEmail, string userPass) {
            this.fileId = fileId;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileStreamResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileStreamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream GetFileStreamResult;
        
        public GetFileStreamResponse() {
        }
        
        public GetFileStreamResponse(System.IO.Stream GetFileStreamResult) {
            this.GetFileStreamResult = GetFileStreamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDirectory", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDirectoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int directoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public GetDirectoryRequest() {
        }
        
        public GetDirectoryRequest(int directoryId, string userEmail, string userPass) {
            this.directoryId = directoryId;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDirectoryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDirectoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Site.FileSystemServiceReference.MyFile GetDirectoryResult;
        
        public GetDirectoryResponse() {
        }
        
        public GetDirectoryResponse(Site.FileSystemServiceReference.MyFile GetDirectoryResult) {
            this.GetDirectoryResult = GetDirectoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int fileId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public GetFileRequest() {
        }
        
        public GetFileRequest(int fileId, string userEmail, string userPass) {
            this.fileId = fileId;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Site.FileSystemServiceReference.MyFile GetFileResult;
        
        public GetFileResponse() {
        }
        
        public GetFileResponse(Site.FileSystemServiceReference.MyFile GetFileResult) {
            this.GetFileResult = GetFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetParentDirectoryId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetParentDirectoryIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int directoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public GetParentDirectoryIdRequest() {
        }
        
        public GetParentDirectoryIdRequest(int directoryId, string userEmail, string userPass) {
            this.directoryId = directoryId;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetParentDirectoryIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetParentDirectoryIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GetParentDirectoryIdResult;
        
        public GetParentDirectoryIdResponse() {
        }
        
        public GetParentDirectoryIdResponse(int GetParentDirectoryIdResult) {
            this.GetParentDirectoryIdResult = GetParentDirectoryIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDirectoryFiles", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDirectoryFilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int directoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool recursive;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public GetDirectoryFilesRequest() {
        }
        
        public GetDirectoryFilesRequest(int directoryId, bool recursive, string userEmail, string userPass) {
            this.directoryId = directoryId;
            this.recursive = recursive;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDirectoryFilesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDirectoryFilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Service", IsNullable=false)]
        public MyFile[] GetDirectoryFilesResult;
        
        public GetDirectoryFilesResponse() {
        }
        
        public GetDirectoryFilesResponse(MyFile[] GetDirectoryFilesResult) {
            this.GetDirectoryFilesResult = GetDirectoryFilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileUploadMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileUploadMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Site.FileSystemServiceReference.MyFile file;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream sourceStream;
        
        public FileUploadMessage() {
        }
        
        public FileUploadMessage(Site.FileSystemServiceReference.MyFile file, string userEmail, string userPass, System.IO.Stream sourceStream) {
            this.file = file;
            this.userEmail = userEmail;
            this.userPass = userPass;
            this.sourceStream = sourceStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse {
        
        public UploadFileResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int fileId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public DeleteFileRequest() {
        }
        
        public DeleteFileRequest(int fileId, string userEmail, string userPass) {
            this.fileId = fileId;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteFileResponse {
        
        public DeleteFileResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateDirectory", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateDirectoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string path;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public CreateDirectoryRequest() {
        }
        
        public CreateDirectoryRequest(string path, string userEmail, string userPass) {
            this.path = path;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateDirectoryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateDirectoryResponse {
        
        public CreateDirectoryResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteDirectory", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteDirectoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int directoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public DeleteDirectoryRequest() {
        }
        
        public DeleteDirectoryRequest(int directoryId, string userEmail, string userPass) {
            this.directoryId = directoryId;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteDirectoryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteDirectoryResponse {
        
        public DeleteDirectoryResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDirectorySubDirectories", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDirectorySubDirectoriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int directoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public GetDirectorySubDirectoriesRequest() {
        }
        
        public GetDirectorySubDirectoriesRequest(int directoryId, string userEmail, string userPass) {
            this.directoryId = directoryId;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDirectorySubDirectoriesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDirectorySubDirectoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Service", IsNullable=false)]
        public DynaTreeNode[] GetDirectorySubDirectoriesResult;
        
        public GetDirectorySubDirectoriesResponse() {
        }
        
        public GetDirectorySubDirectoriesResponse(DynaTreeNode[] GetDirectorySubDirectoriesResult) {
            this.GetDirectorySubDirectoriesResult = GetDirectorySubDirectoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Move", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int fileId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int directoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int isDirectory;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public MoveRequest() {
        }
        
        public MoveRequest(int fileId, int directoryId, int isDirectory, string userEmail, string userPass) {
            this.fileId = fileId;
            this.directoryId = directoryId;
            this.isDirectory = isDirectory;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MoveResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MoveResponse {
        
        public MoveResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Copy", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CopyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int sourceFileId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int outputDirectoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int isDirectory;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public CopyRequest() {
        }
        
        public CopyRequest(int sourceFileId, int outputDirectoryId, int isDirectory, string userEmail, string userPass) {
            this.sourceFileId = sourceFileId;
            this.outputDirectoryId = outputDirectoryId;
            this.isDirectory = isDirectory;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CopyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CopyResponse {
        
        public CopyResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Rename", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RenameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int fileId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string newName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int isDirectory;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public RenameRequest() {
        }
        
        public RenameRequest(int fileId, string newName, int isDirectory, string userEmail, string userPass) {
            this.fileId = fileId;
            this.newName = newName;
            this.isDirectory = isDirectory;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RenameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RenameResponse {
        
        public RenameResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFilePath", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFilePathRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int fileId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int isDirectory;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public GetFilePathRequest() {
        }
        
        public GetFilePathRequest(int fileId, int isDirectory, string userEmail, string userPass) {
            this.fileId = fileId;
            this.isDirectory = isDirectory;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFilePathResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFilePathResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetFilePathResult;
        
        public GetFilePathResponse() {
        }
        
        public GetFilePathResponse(string GetFilePathResult) {
            this.GetFilePathResult = GetFilePathResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileSystemChannel : Site.FileSystemServiceReference.IFileSystem, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileSystemClient : System.ServiceModel.ClientBase<Site.FileSystemServiceReference.IFileSystem>, Site.FileSystemServiceReference.IFileSystem {
        
        public FileSystemClient() {
        }
        
        public FileSystemClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileSystemClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileSystemClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileSystemClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.FileSystemServiceReference.GetAllFilesResponse Site.FileSystemServiceReference.IFileSystem.GetAllFiles(Site.FileSystemServiceReference.GetAllFilesRequest request) {
            return base.Channel.GetAllFiles(request);
        }
        
        public MyFile[] GetAllFiles(string userEmail, string userPass) {
            Site.FileSystemServiceReference.GetAllFilesRequest inValue = new Site.FileSystemServiceReference.GetAllFilesRequest();
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Site.FileSystemServiceReference.GetAllFilesResponse retVal = ((Site.FileSystemServiceReference.IFileSystem)(this)).GetAllFiles(inValue);
            return retVal.GetAllFilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.FileSystemServiceReference.GetFileStreamResponse Site.FileSystemServiceReference.IFileSystem.GetFileStream(Site.FileSystemServiceReference.GetFileStreamRequest request) {
            return base.Channel.GetFileStream(request);
        }
        
        public System.IO.Stream GetFileStream(int fileId, string userEmail, string userPass) {
            Site.FileSystemServiceReference.GetFileStreamRequest inValue = new Site.FileSystemServiceReference.GetFileStreamRequest();
            inValue.fileId = fileId;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Site.FileSystemServiceReference.GetFileStreamResponse retVal = ((Site.FileSystemServiceReference.IFileSystem)(this)).GetFileStream(inValue);
            return retVal.GetFileStreamResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.FileSystemServiceReference.GetDirectoryResponse Site.FileSystemServiceReference.IFileSystem.GetDirectory(Site.FileSystemServiceReference.GetDirectoryRequest request) {
            return base.Channel.GetDirectory(request);
        }
        
        public Site.FileSystemServiceReference.MyFile GetDirectory(int directoryId, string userEmail, string userPass) {
            Site.FileSystemServiceReference.GetDirectoryRequest inValue = new Site.FileSystemServiceReference.GetDirectoryRequest();
            inValue.directoryId = directoryId;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Site.FileSystemServiceReference.GetDirectoryResponse retVal = ((Site.FileSystemServiceReference.IFileSystem)(this)).GetDirectory(inValue);
            return retVal.GetDirectoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.FileSystemServiceReference.GetFileResponse Site.FileSystemServiceReference.IFileSystem.GetFile(Site.FileSystemServiceReference.GetFileRequest request) {
            return base.Channel.GetFile(request);
        }
        
        public Site.FileSystemServiceReference.MyFile GetFile(int fileId, string userEmail, string userPass) {
            Site.FileSystemServiceReference.GetFileRequest inValue = new Site.FileSystemServiceReference.GetFileRequest();
            inValue.fileId = fileId;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Site.FileSystemServiceReference.GetFileResponse retVal = ((Site.FileSystemServiceReference.IFileSystem)(this)).GetFile(inValue);
            return retVal.GetFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.FileSystemServiceReference.GetParentDirectoryIdResponse Site.FileSystemServiceReference.IFileSystem.GetParentDirectoryId(Site.FileSystemServiceReference.GetParentDirectoryIdRequest request) {
            return base.Channel.GetParentDirectoryId(request);
        }
        
        public int GetParentDirectoryId(int directoryId, string userEmail, string userPass) {
            Site.FileSystemServiceReference.GetParentDirectoryIdRequest inValue = new Site.FileSystemServiceReference.GetParentDirectoryIdRequest();
            inValue.directoryId = directoryId;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Site.FileSystemServiceReference.GetParentDirectoryIdResponse retVal = ((Site.FileSystemServiceReference.IFileSystem)(this)).GetParentDirectoryId(inValue);
            return retVal.GetParentDirectoryIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.FileSystemServiceReference.GetDirectoryFilesResponse Site.FileSystemServiceReference.IFileSystem.GetDirectoryFiles(Site.FileSystemServiceReference.GetDirectoryFilesRequest request) {
            return base.Channel.GetDirectoryFiles(request);
        }
        
        public MyFile[] GetDirectoryFiles(int directoryId, bool recursive, string userEmail, string userPass) {
            Site.FileSystemServiceReference.GetDirectoryFilesRequest inValue = new Site.FileSystemServiceReference.GetDirectoryFilesRequest();
            inValue.directoryId = directoryId;
            inValue.recursive = recursive;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Site.FileSystemServiceReference.GetDirectoryFilesResponse retVal = ((Site.FileSystemServiceReference.IFileSystem)(this)).GetDirectoryFiles(inValue);
            return retVal.GetDirectoryFilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.FileSystemServiceReference.UploadFileResponse Site.FileSystemServiceReference.IFileSystem.UploadFile(Site.FileSystemServiceReference.FileUploadMessage request) {
            return base.Channel.UploadFile(request);
        }
        
        public void UploadFile(Site.FileSystemServiceReference.MyFile file, string userEmail, string userPass, System.IO.Stream sourceStream) {
            Site.FileSystemServiceReference.FileUploadMessage inValue = new Site.FileSystemServiceReference.FileUploadMessage();
            inValue.file = file;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            inValue.sourceStream = sourceStream;
            Site.FileSystemServiceReference.UploadFileResponse retVal = ((Site.FileSystemServiceReference.IFileSystem)(this)).UploadFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.FileSystemServiceReference.DeleteFileResponse Site.FileSystemServiceReference.IFileSystem.DeleteFile(Site.FileSystemServiceReference.DeleteFileRequest request) {
            return base.Channel.DeleteFile(request);
        }
        
        public void DeleteFile(int fileId, string userEmail, string userPass) {
            Site.FileSystemServiceReference.DeleteFileRequest inValue = new Site.FileSystemServiceReference.DeleteFileRequest();
            inValue.fileId = fileId;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Site.FileSystemServiceReference.DeleteFileResponse retVal = ((Site.FileSystemServiceReference.IFileSystem)(this)).DeleteFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.FileSystemServiceReference.CreateDirectoryResponse Site.FileSystemServiceReference.IFileSystem.CreateDirectory(Site.FileSystemServiceReference.CreateDirectoryRequest request) {
            return base.Channel.CreateDirectory(request);
        }
        
        public void CreateDirectory(string path, string userEmail, string userPass) {
            Site.FileSystemServiceReference.CreateDirectoryRequest inValue = new Site.FileSystemServiceReference.CreateDirectoryRequest();
            inValue.path = path;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Site.FileSystemServiceReference.CreateDirectoryResponse retVal = ((Site.FileSystemServiceReference.IFileSystem)(this)).CreateDirectory(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.FileSystemServiceReference.DeleteDirectoryResponse Site.FileSystemServiceReference.IFileSystem.DeleteDirectory(Site.FileSystemServiceReference.DeleteDirectoryRequest request) {
            return base.Channel.DeleteDirectory(request);
        }
        
        public void DeleteDirectory(int directoryId, string userEmail, string userPass) {
            Site.FileSystemServiceReference.DeleteDirectoryRequest inValue = new Site.FileSystemServiceReference.DeleteDirectoryRequest();
            inValue.directoryId = directoryId;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Site.FileSystemServiceReference.DeleteDirectoryResponse retVal = ((Site.FileSystemServiceReference.IFileSystem)(this)).DeleteDirectory(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.FileSystemServiceReference.GetDirectorySubDirectoriesResponse Site.FileSystemServiceReference.IFileSystem.GetDirectorySubDirectories(Site.FileSystemServiceReference.GetDirectorySubDirectoriesRequest request) {
            return base.Channel.GetDirectorySubDirectories(request);
        }
        
        public DynaTreeNode[] GetDirectorySubDirectories(int directoryId, string userEmail, string userPass) {
            Site.FileSystemServiceReference.GetDirectorySubDirectoriesRequest inValue = new Site.FileSystemServiceReference.GetDirectorySubDirectoriesRequest();
            inValue.directoryId = directoryId;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Site.FileSystemServiceReference.GetDirectorySubDirectoriesResponse retVal = ((Site.FileSystemServiceReference.IFileSystem)(this)).GetDirectorySubDirectories(inValue);
            return retVal.GetDirectorySubDirectoriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.FileSystemServiceReference.MoveResponse Site.FileSystemServiceReference.IFileSystem.Move(Site.FileSystemServiceReference.MoveRequest request) {
            return base.Channel.Move(request);
        }
        
        public void Move(int fileId, int directoryId, int isDirectory, string userEmail, string userPass) {
            Site.FileSystemServiceReference.MoveRequest inValue = new Site.FileSystemServiceReference.MoveRequest();
            inValue.fileId = fileId;
            inValue.directoryId = directoryId;
            inValue.isDirectory = isDirectory;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Site.FileSystemServiceReference.MoveResponse retVal = ((Site.FileSystemServiceReference.IFileSystem)(this)).Move(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.FileSystemServiceReference.CopyResponse Site.FileSystemServiceReference.IFileSystem.Copy(Site.FileSystemServiceReference.CopyRequest request) {
            return base.Channel.Copy(request);
        }
        
        public void Copy(int sourceFileId, int outputDirectoryId, int isDirectory, string userEmail, string userPass) {
            Site.FileSystemServiceReference.CopyRequest inValue = new Site.FileSystemServiceReference.CopyRequest();
            inValue.sourceFileId = sourceFileId;
            inValue.outputDirectoryId = outputDirectoryId;
            inValue.isDirectory = isDirectory;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Site.FileSystemServiceReference.CopyResponse retVal = ((Site.FileSystemServiceReference.IFileSystem)(this)).Copy(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.FileSystemServiceReference.RenameResponse Site.FileSystemServiceReference.IFileSystem.Rename(Site.FileSystemServiceReference.RenameRequest request) {
            return base.Channel.Rename(request);
        }
        
        public void Rename(int fileId, string newName, int isDirectory, string userEmail, string userPass) {
            Site.FileSystemServiceReference.RenameRequest inValue = new Site.FileSystemServiceReference.RenameRequest();
            inValue.fileId = fileId;
            inValue.newName = newName;
            inValue.isDirectory = isDirectory;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Site.FileSystemServiceReference.RenameResponse retVal = ((Site.FileSystemServiceReference.IFileSystem)(this)).Rename(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Site.FileSystemServiceReference.GetFilePathResponse Site.FileSystemServiceReference.IFileSystem.GetFilePath(Site.FileSystemServiceReference.GetFilePathRequest request) {
            return base.Channel.GetFilePath(request);
        }
        
        public string GetFilePath(int fileId, int isDirectory, string userEmail, string userPass) {
            Site.FileSystemServiceReference.GetFilePathRequest inValue = new Site.FileSystemServiceReference.GetFilePathRequest();
            inValue.fileId = fileId;
            inValue.isDirectory = isDirectory;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            Site.FileSystemServiceReference.GetFilePathResponse retVal = ((Site.FileSystemServiceReference.IFileSystem)(this)).GetFilePath(inValue);
            return retVal.GetFilePathResult;
        }
    }
}
