//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminTool.FileSystemServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileSystemServiceReference.IFileSystem")]
    public interface IFileSystem {
        
        // CODEGEN: Parameter 'GetAllFilesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetAllFiles", ReplyAction="http://tempuri.org/IFileSystem/GetAllFilesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AdminTool.FileSystemServiceReference.GetAllFilesResponse GetAllFiles(AdminTool.FileSystemServiceReference.GetAllFilesRequest request);
        
        // CODEGEN: Parameter 'userEmail' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetFileStream", ReplyAction="http://tempuri.org/IFileSystem/GetFileStreamResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AdminTool.FileSystemServiceReference.GetFileStreamResponse GetFileStream(AdminTool.FileSystemServiceReference.GetFileStreamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetPublicFileStream", ReplyAction="http://tempuri.org/IFileSystem/GetPublicFileStreamResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IO.Stream GetPublicFileStream(int fileId, int userId);
        
        // CODEGEN: Parameter 'userEmail' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetDirectory", ReplyAction="http://tempuri.org/IFileSystem/GetDirectoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AdminTool.FileSystemServiceReference.GetDirectoryResponse GetDirectory(AdminTool.FileSystemServiceReference.GetDirectoryRequest request);
        
        // CODEGEN: Parameter 'userEmail' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetFile", ReplyAction="http://tempuri.org/IFileSystem/GetFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AdminTool.FileSystemServiceReference.GetFileResponse GetFile(AdminTool.FileSystemServiceReference.GetFileRequest request);
        
        // CODEGEN: Parameter 'userEmail' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetParentDirectoryId", ReplyAction="http://tempuri.org/IFileSystem/GetParentDirectoryIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AdminTool.FileSystemServiceReference.GetParentDirectoryIdResponse GetParentDirectoryId(AdminTool.FileSystemServiceReference.GetParentDirectoryIdRequest request);
        
        // CODEGEN: Parameter 'GetDirectoryFilesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetDirectoryFiles", ReplyAction="http://tempuri.org/IFileSystem/GetDirectoryFilesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AdminTool.FileSystemServiceReference.GetDirectoryFilesResponse GetDirectoryFiles(AdminTool.FileSystemServiceReference.GetDirectoryFilesRequest request);
        
        // CODEGEN: Parameter 'GetDirectoryFilesOperatorResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetDirectoryFilesOperator", ReplyAction="http://tempuri.org/IFileSystem/GetDirectoryFilesOperatorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AdminTool.FileSystemServiceReference.GetDirectoryFilesOperatorResponse GetDirectoryFilesOperator(AdminTool.FileSystemServiceReference.GetDirectoryFilesOperatorRequest request);
        
        // CODEGEN: Generating message contract since the operation UploadFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/UploadFile", ReplyAction="http://tempuri.org/IFileSystem/UploadFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AdminTool.FileSystemServiceReference.UploadFileResponse UploadFile(AdminTool.FileSystemServiceReference.FileUploadMessage request);
        
        // CODEGEN: Parameter 'userEmail' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/DeleteFile", ReplyAction="http://tempuri.org/IFileSystem/DeleteFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AdminTool.FileSystemServiceReference.DeleteFileResponse DeleteFile(AdminTool.FileSystemServiceReference.DeleteFileRequest request);
        
        // CODEGEN: Parameter 'path' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/CreateDirectory", ReplyAction="http://tempuri.org/IFileSystem/CreateDirectoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AdminTool.FileSystemServiceReference.CreateDirectoryResponse CreateDirectory(AdminTool.FileSystemServiceReference.CreateDirectoryRequest request);
        
        // CODEGEN: Parameter 'userEmail' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/DeleteDirectory", ReplyAction="http://tempuri.org/IFileSystem/DeleteDirectoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AdminTool.FileSystemServiceReference.DeleteDirectoryResponse DeleteDirectory(AdminTool.FileSystemServiceReference.DeleteDirectoryRequest request);
        
        // CODEGEN: Parameter 'GetDirectorySubDirectoriesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetDirectorySubDirectories", ReplyAction="http://tempuri.org/IFileSystem/GetDirectorySubDirectoriesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AdminTool.FileSystemServiceReference.GetDirectorySubDirectoriesResponse GetDirectorySubDirectories(AdminTool.FileSystemServiceReference.GetDirectorySubDirectoriesRequest request);
        
        // CODEGEN: Parameter 'userEmail' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/Move", ReplyAction="http://tempuri.org/IFileSystem/MoveResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AdminTool.FileSystemServiceReference.MoveResponse Move(AdminTool.FileSystemServiceReference.MoveRequest request);
        
        // CODEGEN: Parameter 'userEmail' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/Copy", ReplyAction="http://tempuri.org/IFileSystem/CopyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AdminTool.FileSystemServiceReference.CopyResponse Copy(AdminTool.FileSystemServiceReference.CopyRequest request);
        
        // CODEGEN: Parameter 'newName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/Rename", ReplyAction="http://tempuri.org/IFileSystem/RenameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AdminTool.FileSystemServiceReference.RenameResponse Rename(AdminTool.FileSystemServiceReference.RenameRequest request);
        
        // CODEGEN: Parameter 'GetFilePathResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetFilePath", ReplyAction="http://tempuri.org/IFileSystem/GetFilePathResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AdminTool.FileSystemServiceReference.GetFilePathResponse GetFilePath(AdminTool.FileSystemServiceReference.GetFilePathRequest request);
        
        // CODEGEN: Parameter 'userEmail' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/CanUploadFile", ReplyAction="http://tempuri.org/IFileSystem/CanUploadFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AdminTool.FileSystemServiceReference.CanUploadFileResponse CanUploadFile(AdminTool.FileSystemServiceReference.CanUploadFileRequest request);
        
        // CODEGEN: Parameter 'operatorLogin' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSystem/GetUserDirectoryTree", ReplyAction="http://tempuri.org/IFileSystem/GetUserDirectoryTreeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AdminTool.FileSystemServiceReference.GetUserDirectoryTreeResponse GetUserDirectoryTree(AdminTool.FileSystemServiceReference.GetUserDirectoryTreeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Service")]
    public partial class MyFile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int fileIdField;
        
        private bool fileIdFieldSpecified;
        
        private bool isDirectoryField;
        
        private bool isDirectoryFieldSpecified;
        
        private bool isPublicField;
        
        private bool isPublicFieldSpecified;
        
        private System.DateTime lastWriteTimeField;
        
        private bool lastWriteTimeFieldSpecified;
        
        private string nameField;
        
        private int parentDirectoryIdField;
        
        private bool parentDirectoryIdFieldSpecified;
        
        private string pathField;
        
        private long sizeField;
        
        private bool sizeFieldSpecified;
        
        private int userIdField;
        
        private bool userIdFieldSpecified;
        
        private FileStatus statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int FileId {
            get {
                return this.fileIdField;
            }
            set {
                this.fileIdField = value;
                this.RaisePropertyChanged("FileId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FileIdSpecified {
            get {
                return this.fileIdFieldSpecified;
            }
            set {
                this.fileIdFieldSpecified = value;
                this.RaisePropertyChanged("FileIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool IsDirectory {
            get {
                return this.isDirectoryField;
            }
            set {
                this.isDirectoryField = value;
                this.RaisePropertyChanged("IsDirectory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsDirectorySpecified {
            get {
                return this.isDirectoryFieldSpecified;
            }
            set {
                this.isDirectoryFieldSpecified = value;
                this.RaisePropertyChanged("IsDirectorySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsPublic {
            get {
                return this.isPublicField;
            }
            set {
                this.isPublicField = value;
                this.RaisePropertyChanged("IsPublic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsPublicSpecified {
            get {
                return this.isPublicFieldSpecified;
            }
            set {
                this.isPublicFieldSpecified = value;
                this.RaisePropertyChanged("IsPublicSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime LastWriteTime {
            get {
                return this.lastWriteTimeField;
            }
            set {
                this.lastWriteTimeField = value;
                this.RaisePropertyChanged("LastWriteTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastWriteTimeSpecified {
            get {
                return this.lastWriteTimeFieldSpecified;
            }
            set {
                this.lastWriteTimeFieldSpecified = value;
                this.RaisePropertyChanged("LastWriteTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int ParentDirectoryId {
            get {
                return this.parentDirectoryIdField;
            }
            set {
                this.parentDirectoryIdField = value;
                this.RaisePropertyChanged("ParentDirectoryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ParentDirectoryIdSpecified {
            get {
                return this.parentDirectoryIdFieldSpecified;
            }
            set {
                this.parentDirectoryIdFieldSpecified = value;
                this.RaisePropertyChanged("ParentDirectoryIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
                this.RaisePropertyChanged("Path");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("Size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SizeSpecified {
            get {
                return this.sizeFieldSpecified;
            }
            set {
                this.sizeFieldSpecified = value;
                this.RaisePropertyChanged("SizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UserIdSpecified {
            get {
                return this.userIdFieldSpecified;
            }
            set {
                this.userIdFieldSpecified = value;
                this.RaisePropertyChanged("UserIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public FileStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Service")]
    public enum FileStatus {
        
        /// <remarks/>
        Download,
        
        /// <remarks/>
        Upload,
        
        /// <remarks/>
        Delete,
        
        /// <remarks/>
        NotChange,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Service")]
    public partial class DirectoryTree : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DirectoryTree[] childTreeField;
        
        private int directoryIdField;
        
        private bool directoryIdFieldSpecified;
        
        private string nameField;
        
        private int parentIdField;
        
        private bool parentIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DirectoryTree[] ChildTree {
            get {
                return this.childTreeField;
            }
            set {
                this.childTreeField = value;
                this.RaisePropertyChanged("ChildTree");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int DirectoryId {
            get {
                return this.directoryIdField;
            }
            set {
                this.directoryIdField = value;
                this.RaisePropertyChanged("DirectoryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DirectoryIdSpecified {
            get {
                return this.directoryIdFieldSpecified;
            }
            set {
                this.directoryIdFieldSpecified = value;
                this.RaisePropertyChanged("DirectoryIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ParentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
                this.RaisePropertyChanged("ParentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ParentIdSpecified {
            get {
                return this.parentIdFieldSpecified;
            }
            set {
                this.parentIdFieldSpecified = value;
                this.RaisePropertyChanged("ParentIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Service")]
    public partial class DynaTreeNode : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isFolderField;
        
        private bool isFolderFieldSpecified;
        
        private bool isLazyField;
        
        private bool isLazyFieldSpecified;
        
        private int keyField;
        
        private bool keyFieldSpecified;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool isFolder {
            get {
                return this.isFolderField;
            }
            set {
                this.isFolderField = value;
                this.RaisePropertyChanged("isFolder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isFolderSpecified {
            get {
                return this.isFolderFieldSpecified;
            }
            set {
                this.isFolderFieldSpecified = value;
                this.RaisePropertyChanged("isFolderSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool isLazy {
            get {
                return this.isLazyField;
            }
            set {
                this.isLazyField = value;
                this.RaisePropertyChanged("isLazy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isLazySpecified {
            get {
                return this.isLazyFieldSpecified;
            }
            set {
                this.isLazyFieldSpecified = value;
                this.RaisePropertyChanged("isLazySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool keySpecified {
            get {
                return this.keyFieldSpecified;
            }
            set {
                this.keyFieldSpecified = value;
                this.RaisePropertyChanged("keySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllFiles", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllFilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public GetAllFilesRequest() {
        }
        
        public GetAllFilesRequest(string userEmail, string userPass) {
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllFilesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllFilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Service", IsNullable=false)]
        public MyFile[] GetAllFilesResult;
        
        public GetAllFilesResponse() {
        }
        
        public GetAllFilesResponse(MyFile[] GetAllFilesResult) {
            this.GetAllFilesResult = GetAllFilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileStream", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileStreamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int fileId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public GetFileStreamRequest() {
        }
        
        public GetFileStreamRequest(int fileId, string userEmail, string userPass) {
            this.fileId = fileId;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileStreamResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileStreamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream GetFileStreamResult;
        
        public GetFileStreamResponse() {
        }
        
        public GetFileStreamResponse(System.IO.Stream GetFileStreamResult) {
            this.GetFileStreamResult = GetFileStreamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDirectory", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDirectoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int directoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public GetDirectoryRequest() {
        }
        
        public GetDirectoryRequest(int directoryId, string userEmail, string userPass) {
            this.directoryId = directoryId;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDirectoryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDirectoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AdminTool.FileSystemServiceReference.MyFile GetDirectoryResult;
        
        public GetDirectoryResponse() {
        }
        
        public GetDirectoryResponse(AdminTool.FileSystemServiceReference.MyFile GetDirectoryResult) {
            this.GetDirectoryResult = GetDirectoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int fileId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public GetFileRequest() {
        }
        
        public GetFileRequest(int fileId, string userEmail, string userPass) {
            this.fileId = fileId;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AdminTool.FileSystemServiceReference.MyFile GetFileResult;
        
        public GetFileResponse() {
        }
        
        public GetFileResponse(AdminTool.FileSystemServiceReference.MyFile GetFileResult) {
            this.GetFileResult = GetFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetParentDirectoryId", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetParentDirectoryIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int directoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public GetParentDirectoryIdRequest() {
        }
        
        public GetParentDirectoryIdRequest(int directoryId, string userEmail, string userPass) {
            this.directoryId = directoryId;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetParentDirectoryIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetParentDirectoryIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GetParentDirectoryIdResult;
        
        public GetParentDirectoryIdResponse() {
        }
        
        public GetParentDirectoryIdResponse(int GetParentDirectoryIdResult) {
            this.GetParentDirectoryIdResult = GetParentDirectoryIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDirectoryFiles", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDirectoryFilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int directoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool recursive;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public GetDirectoryFilesRequest() {
        }
        
        public GetDirectoryFilesRequest(int directoryId, bool recursive, string userEmail, string userPass) {
            this.directoryId = directoryId;
            this.recursive = recursive;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDirectoryFilesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDirectoryFilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Service", IsNullable=false)]
        public MyFile[] GetDirectoryFilesResult;
        
        public GetDirectoryFilesResponse() {
        }
        
        public GetDirectoryFilesResponse(MyFile[] GetDirectoryFilesResult) {
            this.GetDirectoryFilesResult = GetDirectoryFilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDirectoryFilesOperator", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDirectoryFilesOperatorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int directoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string operatorLogin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string operatorPass;
        
        public GetDirectoryFilesOperatorRequest() {
        }
        
        public GetDirectoryFilesOperatorRequest(int directoryId, int userId, string operatorLogin, string operatorPass) {
            this.directoryId = directoryId;
            this.userId = userId;
            this.operatorLogin = operatorLogin;
            this.operatorPass = operatorPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDirectoryFilesOperatorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDirectoryFilesOperatorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Service", IsNullable=false)]
        public MyFile[] GetDirectoryFilesOperatorResult;
        
        public GetDirectoryFilesOperatorResponse() {
        }
        
        public GetDirectoryFilesOperatorResponse(MyFile[] GetDirectoryFilesOperatorResult) {
            this.GetDirectoryFilesOperatorResult = GetDirectoryFilesOperatorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileUploadMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileUploadMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public AdminTool.FileSystemServiceReference.MyFile file;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream sourceStream;
        
        public FileUploadMessage() {
        }
        
        public FileUploadMessage(AdminTool.FileSystemServiceReference.MyFile file, string userEmail, string userPass, System.IO.Stream sourceStream) {
            this.file = file;
            this.userEmail = userEmail;
            this.userPass = userPass;
            this.sourceStream = sourceStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse {
        
        public UploadFileResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int fileId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public DeleteFileRequest() {
        }
        
        public DeleteFileRequest(int fileId, string userEmail, string userPass) {
            this.fileId = fileId;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteFileResponse {
        
        public DeleteFileResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateDirectory", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateDirectoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string path;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public CreateDirectoryRequest() {
        }
        
        public CreateDirectoryRequest(string path, string userEmail, string userPass) {
            this.path = path;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateDirectoryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateDirectoryResponse {
        
        public CreateDirectoryResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteDirectory", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteDirectoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int directoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public DeleteDirectoryRequest() {
        }
        
        public DeleteDirectoryRequest(int directoryId, string userEmail, string userPass) {
            this.directoryId = directoryId;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteDirectoryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteDirectoryResponse {
        
        public DeleteDirectoryResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDirectorySubDirectories", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDirectorySubDirectoriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int directoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public GetDirectorySubDirectoriesRequest() {
        }
        
        public GetDirectorySubDirectoriesRequest(int directoryId, string userEmail, string userPass) {
            this.directoryId = directoryId;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDirectorySubDirectoriesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDirectorySubDirectoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server.Service", IsNullable=false)]
        public DynaTreeNode[] GetDirectorySubDirectoriesResult;
        
        public GetDirectorySubDirectoriesResponse() {
        }
        
        public GetDirectorySubDirectoriesResponse(DynaTreeNode[] GetDirectorySubDirectoriesResult) {
            this.GetDirectorySubDirectoriesResult = GetDirectorySubDirectoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Move", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int fileId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int directoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int isDirectory;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public MoveRequest() {
        }
        
        public MoveRequest(int fileId, int directoryId, int isDirectory, string userEmail, string userPass) {
            this.fileId = fileId;
            this.directoryId = directoryId;
            this.isDirectory = isDirectory;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MoveResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class MoveResponse {
        
        public MoveResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Copy", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CopyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int sourceFileId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int outputDirectoryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int isDirectory;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public CopyRequest() {
        }
        
        public CopyRequest(int sourceFileId, int outputDirectoryId, int isDirectory, string userEmail, string userPass) {
            this.sourceFileId = sourceFileId;
            this.outputDirectoryId = outputDirectoryId;
            this.isDirectory = isDirectory;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CopyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CopyResponse {
        
        public CopyResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Rename", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RenameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int fileId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string newName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int isDirectory;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public RenameRequest() {
        }
        
        public RenameRequest(int fileId, string newName, int isDirectory, string userEmail, string userPass) {
            this.fileId = fileId;
            this.newName = newName;
            this.isDirectory = isDirectory;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RenameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RenameResponse {
        
        public RenameResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFilePath", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFilePathRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int fileId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int isDirectory;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public GetFilePathRequest() {
        }
        
        public GetFilePathRequest(int fileId, int isDirectory, string userEmail, string userPass) {
            this.fileId = fileId;
            this.isDirectory = isDirectory;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFilePathResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFilePathResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetFilePathResult;
        
        public GetFilePathResponse() {
        }
        
        public GetFilePathResponse(string GetFilePathResult) {
            this.GetFilePathResult = GetFilePathResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CanUploadFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CanUploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long fileSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userEmail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userPass;
        
        public CanUploadFileRequest() {
        }
        
        public CanUploadFileRequest(long fileSize, string userEmail, string userPass) {
            this.fileSize = fileSize;
            this.userEmail = userEmail;
            this.userPass = userPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CanUploadFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CanUploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CanUploadFileResult;
        
        public CanUploadFileResponse() {
        }
        
        public CanUploadFileResponse(bool CanUploadFileResult) {
            this.CanUploadFileResult = CanUploadFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserDirectoryTree", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserDirectoryTreeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string operatorLogin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string operatorPass;
        
        public GetUserDirectoryTreeRequest() {
        }
        
        public GetUserDirectoryTreeRequest(int userId, string operatorLogin, string operatorPass) {
            this.userId = userId;
            this.operatorLogin = operatorLogin;
            this.operatorPass = operatorPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserDirectoryTreeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserDirectoryTreeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AdminTool.FileSystemServiceReference.DirectoryTree GetUserDirectoryTreeResult;
        
        public GetUserDirectoryTreeResponse() {
        }
        
        public GetUserDirectoryTreeResponse(AdminTool.FileSystemServiceReference.DirectoryTree GetUserDirectoryTreeResult) {
            this.GetUserDirectoryTreeResult = GetUserDirectoryTreeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileSystemChannel : AdminTool.FileSystemServiceReference.IFileSystem, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileSystemClient : System.ServiceModel.ClientBase<AdminTool.FileSystemServiceReference.IFileSystem>, AdminTool.FileSystemServiceReference.IFileSystem {
        
        public FileSystemClient() {
        }
        
        public FileSystemClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileSystemClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileSystemClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileSystemClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminTool.FileSystemServiceReference.GetAllFilesResponse AdminTool.FileSystemServiceReference.IFileSystem.GetAllFiles(AdminTool.FileSystemServiceReference.GetAllFilesRequest request) {
            return base.Channel.GetAllFiles(request);
        }
        
        public MyFile[] GetAllFiles(string userEmail, string userPass) {
            AdminTool.FileSystemServiceReference.GetAllFilesRequest inValue = new AdminTool.FileSystemServiceReference.GetAllFilesRequest();
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            AdminTool.FileSystemServiceReference.GetAllFilesResponse retVal = ((AdminTool.FileSystemServiceReference.IFileSystem)(this)).GetAllFiles(inValue);
            return retVal.GetAllFilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminTool.FileSystemServiceReference.GetFileStreamResponse AdminTool.FileSystemServiceReference.IFileSystem.GetFileStream(AdminTool.FileSystemServiceReference.GetFileStreamRequest request) {
            return base.Channel.GetFileStream(request);
        }
        
        public System.IO.Stream GetFileStream(int fileId, string userEmail, string userPass) {
            AdminTool.FileSystemServiceReference.GetFileStreamRequest inValue = new AdminTool.FileSystemServiceReference.GetFileStreamRequest();
            inValue.fileId = fileId;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            AdminTool.FileSystemServiceReference.GetFileStreamResponse retVal = ((AdminTool.FileSystemServiceReference.IFileSystem)(this)).GetFileStream(inValue);
            return retVal.GetFileStreamResult;
        }
        
        public System.IO.Stream GetPublicFileStream(int fileId, int userId) {
            return base.Channel.GetPublicFileStream(fileId, userId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminTool.FileSystemServiceReference.GetDirectoryResponse AdminTool.FileSystemServiceReference.IFileSystem.GetDirectory(AdminTool.FileSystemServiceReference.GetDirectoryRequest request) {
            return base.Channel.GetDirectory(request);
        }
        
        public AdminTool.FileSystemServiceReference.MyFile GetDirectory(int directoryId, string userEmail, string userPass) {
            AdminTool.FileSystemServiceReference.GetDirectoryRequest inValue = new AdminTool.FileSystemServiceReference.GetDirectoryRequest();
            inValue.directoryId = directoryId;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            AdminTool.FileSystemServiceReference.GetDirectoryResponse retVal = ((AdminTool.FileSystemServiceReference.IFileSystem)(this)).GetDirectory(inValue);
            return retVal.GetDirectoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminTool.FileSystemServiceReference.GetFileResponse AdminTool.FileSystemServiceReference.IFileSystem.GetFile(AdminTool.FileSystemServiceReference.GetFileRequest request) {
            return base.Channel.GetFile(request);
        }
        
        public AdminTool.FileSystemServiceReference.MyFile GetFile(int fileId, string userEmail, string userPass) {
            AdminTool.FileSystemServiceReference.GetFileRequest inValue = new AdminTool.FileSystemServiceReference.GetFileRequest();
            inValue.fileId = fileId;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            AdminTool.FileSystemServiceReference.GetFileResponse retVal = ((AdminTool.FileSystemServiceReference.IFileSystem)(this)).GetFile(inValue);
            return retVal.GetFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminTool.FileSystemServiceReference.GetParentDirectoryIdResponse AdminTool.FileSystemServiceReference.IFileSystem.GetParentDirectoryId(AdminTool.FileSystemServiceReference.GetParentDirectoryIdRequest request) {
            return base.Channel.GetParentDirectoryId(request);
        }
        
        public int GetParentDirectoryId(int directoryId, string userEmail, string userPass) {
            AdminTool.FileSystemServiceReference.GetParentDirectoryIdRequest inValue = new AdminTool.FileSystemServiceReference.GetParentDirectoryIdRequest();
            inValue.directoryId = directoryId;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            AdminTool.FileSystemServiceReference.GetParentDirectoryIdResponse retVal = ((AdminTool.FileSystemServiceReference.IFileSystem)(this)).GetParentDirectoryId(inValue);
            return retVal.GetParentDirectoryIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminTool.FileSystemServiceReference.GetDirectoryFilesResponse AdminTool.FileSystemServiceReference.IFileSystem.GetDirectoryFiles(AdminTool.FileSystemServiceReference.GetDirectoryFilesRequest request) {
            return base.Channel.GetDirectoryFiles(request);
        }
        
        public MyFile[] GetDirectoryFiles(int directoryId, bool recursive, string userEmail, string userPass) {
            AdminTool.FileSystemServiceReference.GetDirectoryFilesRequest inValue = new AdminTool.FileSystemServiceReference.GetDirectoryFilesRequest();
            inValue.directoryId = directoryId;
            inValue.recursive = recursive;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            AdminTool.FileSystemServiceReference.GetDirectoryFilesResponse retVal = ((AdminTool.FileSystemServiceReference.IFileSystem)(this)).GetDirectoryFiles(inValue);
            return retVal.GetDirectoryFilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminTool.FileSystemServiceReference.GetDirectoryFilesOperatorResponse AdminTool.FileSystemServiceReference.IFileSystem.GetDirectoryFilesOperator(AdminTool.FileSystemServiceReference.GetDirectoryFilesOperatorRequest request) {
            return base.Channel.GetDirectoryFilesOperator(request);
        }
        
        public MyFile[] GetDirectoryFilesOperator(int directoryId, int userId, string operatorLogin, string operatorPass) {
            AdminTool.FileSystemServiceReference.GetDirectoryFilesOperatorRequest inValue = new AdminTool.FileSystemServiceReference.GetDirectoryFilesOperatorRequest();
            inValue.directoryId = directoryId;
            inValue.userId = userId;
            inValue.operatorLogin = operatorLogin;
            inValue.operatorPass = operatorPass;
            AdminTool.FileSystemServiceReference.GetDirectoryFilesOperatorResponse retVal = ((AdminTool.FileSystemServiceReference.IFileSystem)(this)).GetDirectoryFilesOperator(inValue);
            return retVal.GetDirectoryFilesOperatorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminTool.FileSystemServiceReference.UploadFileResponse AdminTool.FileSystemServiceReference.IFileSystem.UploadFile(AdminTool.FileSystemServiceReference.FileUploadMessage request) {
            return base.Channel.UploadFile(request);
        }
        
        public void UploadFile(AdminTool.FileSystemServiceReference.MyFile file, string userEmail, string userPass, System.IO.Stream sourceStream) {
            AdminTool.FileSystemServiceReference.FileUploadMessage inValue = new AdminTool.FileSystemServiceReference.FileUploadMessage();
            inValue.file = file;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            inValue.sourceStream = sourceStream;
            AdminTool.FileSystemServiceReference.UploadFileResponse retVal = ((AdminTool.FileSystemServiceReference.IFileSystem)(this)).UploadFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminTool.FileSystemServiceReference.DeleteFileResponse AdminTool.FileSystemServiceReference.IFileSystem.DeleteFile(AdminTool.FileSystemServiceReference.DeleteFileRequest request) {
            return base.Channel.DeleteFile(request);
        }
        
        public void DeleteFile(int fileId, string userEmail, string userPass) {
            AdminTool.FileSystemServiceReference.DeleteFileRequest inValue = new AdminTool.FileSystemServiceReference.DeleteFileRequest();
            inValue.fileId = fileId;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            AdminTool.FileSystemServiceReference.DeleteFileResponse retVal = ((AdminTool.FileSystemServiceReference.IFileSystem)(this)).DeleteFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminTool.FileSystemServiceReference.CreateDirectoryResponse AdminTool.FileSystemServiceReference.IFileSystem.CreateDirectory(AdminTool.FileSystemServiceReference.CreateDirectoryRequest request) {
            return base.Channel.CreateDirectory(request);
        }
        
        public void CreateDirectory(string path, string userEmail, string userPass) {
            AdminTool.FileSystemServiceReference.CreateDirectoryRequest inValue = new AdminTool.FileSystemServiceReference.CreateDirectoryRequest();
            inValue.path = path;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            AdminTool.FileSystemServiceReference.CreateDirectoryResponse retVal = ((AdminTool.FileSystemServiceReference.IFileSystem)(this)).CreateDirectory(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminTool.FileSystemServiceReference.DeleteDirectoryResponse AdminTool.FileSystemServiceReference.IFileSystem.DeleteDirectory(AdminTool.FileSystemServiceReference.DeleteDirectoryRequest request) {
            return base.Channel.DeleteDirectory(request);
        }
        
        public void DeleteDirectory(int directoryId, string userEmail, string userPass) {
            AdminTool.FileSystemServiceReference.DeleteDirectoryRequest inValue = new AdminTool.FileSystemServiceReference.DeleteDirectoryRequest();
            inValue.directoryId = directoryId;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            AdminTool.FileSystemServiceReference.DeleteDirectoryResponse retVal = ((AdminTool.FileSystemServiceReference.IFileSystem)(this)).DeleteDirectory(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminTool.FileSystemServiceReference.GetDirectorySubDirectoriesResponse AdminTool.FileSystemServiceReference.IFileSystem.GetDirectorySubDirectories(AdminTool.FileSystemServiceReference.GetDirectorySubDirectoriesRequest request) {
            return base.Channel.GetDirectorySubDirectories(request);
        }
        
        public DynaTreeNode[] GetDirectorySubDirectories(int directoryId, string userEmail, string userPass) {
            AdminTool.FileSystemServiceReference.GetDirectorySubDirectoriesRequest inValue = new AdminTool.FileSystemServiceReference.GetDirectorySubDirectoriesRequest();
            inValue.directoryId = directoryId;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            AdminTool.FileSystemServiceReference.GetDirectorySubDirectoriesResponse retVal = ((AdminTool.FileSystemServiceReference.IFileSystem)(this)).GetDirectorySubDirectories(inValue);
            return retVal.GetDirectorySubDirectoriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminTool.FileSystemServiceReference.MoveResponse AdminTool.FileSystemServiceReference.IFileSystem.Move(AdminTool.FileSystemServiceReference.MoveRequest request) {
            return base.Channel.Move(request);
        }
        
        public void Move(int fileId, int directoryId, int isDirectory, string userEmail, string userPass) {
            AdminTool.FileSystemServiceReference.MoveRequest inValue = new AdminTool.FileSystemServiceReference.MoveRequest();
            inValue.fileId = fileId;
            inValue.directoryId = directoryId;
            inValue.isDirectory = isDirectory;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            AdminTool.FileSystemServiceReference.MoveResponse retVal = ((AdminTool.FileSystemServiceReference.IFileSystem)(this)).Move(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminTool.FileSystemServiceReference.CopyResponse AdminTool.FileSystemServiceReference.IFileSystem.Copy(AdminTool.FileSystemServiceReference.CopyRequest request) {
            return base.Channel.Copy(request);
        }
        
        public void Copy(int sourceFileId, int outputDirectoryId, int isDirectory, string userEmail, string userPass) {
            AdminTool.FileSystemServiceReference.CopyRequest inValue = new AdminTool.FileSystemServiceReference.CopyRequest();
            inValue.sourceFileId = sourceFileId;
            inValue.outputDirectoryId = outputDirectoryId;
            inValue.isDirectory = isDirectory;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            AdminTool.FileSystemServiceReference.CopyResponse retVal = ((AdminTool.FileSystemServiceReference.IFileSystem)(this)).Copy(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminTool.FileSystemServiceReference.RenameResponse AdminTool.FileSystemServiceReference.IFileSystem.Rename(AdminTool.FileSystemServiceReference.RenameRequest request) {
            return base.Channel.Rename(request);
        }
        
        public void Rename(int fileId, string newName, int isDirectory, string userEmail, string userPass) {
            AdminTool.FileSystemServiceReference.RenameRequest inValue = new AdminTool.FileSystemServiceReference.RenameRequest();
            inValue.fileId = fileId;
            inValue.newName = newName;
            inValue.isDirectory = isDirectory;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            AdminTool.FileSystemServiceReference.RenameResponse retVal = ((AdminTool.FileSystemServiceReference.IFileSystem)(this)).Rename(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminTool.FileSystemServiceReference.GetFilePathResponse AdminTool.FileSystemServiceReference.IFileSystem.GetFilePath(AdminTool.FileSystemServiceReference.GetFilePathRequest request) {
            return base.Channel.GetFilePath(request);
        }
        
        public string GetFilePath(int fileId, int isDirectory, string userEmail, string userPass) {
            AdminTool.FileSystemServiceReference.GetFilePathRequest inValue = new AdminTool.FileSystemServiceReference.GetFilePathRequest();
            inValue.fileId = fileId;
            inValue.isDirectory = isDirectory;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            AdminTool.FileSystemServiceReference.GetFilePathResponse retVal = ((AdminTool.FileSystemServiceReference.IFileSystem)(this)).GetFilePath(inValue);
            return retVal.GetFilePathResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminTool.FileSystemServiceReference.CanUploadFileResponse AdminTool.FileSystemServiceReference.IFileSystem.CanUploadFile(AdminTool.FileSystemServiceReference.CanUploadFileRequest request) {
            return base.Channel.CanUploadFile(request);
        }
        
        public bool CanUploadFile(long fileSize, string userEmail, string userPass) {
            AdminTool.FileSystemServiceReference.CanUploadFileRequest inValue = new AdminTool.FileSystemServiceReference.CanUploadFileRequest();
            inValue.fileSize = fileSize;
            inValue.userEmail = userEmail;
            inValue.userPass = userPass;
            AdminTool.FileSystemServiceReference.CanUploadFileResponse retVal = ((AdminTool.FileSystemServiceReference.IFileSystem)(this)).CanUploadFile(inValue);
            return retVal.CanUploadFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AdminTool.FileSystemServiceReference.GetUserDirectoryTreeResponse AdminTool.FileSystemServiceReference.IFileSystem.GetUserDirectoryTree(AdminTool.FileSystemServiceReference.GetUserDirectoryTreeRequest request) {
            return base.Channel.GetUserDirectoryTree(request);
        }
        
        public AdminTool.FileSystemServiceReference.DirectoryTree GetUserDirectoryTree(int userId, string operatorLogin, string operatorPass) {
            AdminTool.FileSystemServiceReference.GetUserDirectoryTreeRequest inValue = new AdminTool.FileSystemServiceReference.GetUserDirectoryTreeRequest();
            inValue.userId = userId;
            inValue.operatorLogin = operatorLogin;
            inValue.operatorPass = operatorPass;
            AdminTool.FileSystemServiceReference.GetUserDirectoryTreeResponse retVal = ((AdminTool.FileSystemServiceReference.IFileSystem)(this)).GetUserDirectoryTree(inValue);
            return retVal.GetUserDirectoryTreeResult;
        }
    }
}
